//
// Created by rzhig on 04.03.2022.
//

#ifndef QUASIGROUP_JMQUASIGROUP_H
#define QUASIGROUP_JMQUASIGROUP_H

#include <iostream>
#include <fstream>

#include "IncidenceCube.h"
#include "Quasigroup.h"

namespace Quasigroup {

    /*
     * Quasigroups given by the Latin square and
     * generated by the Jacobson Matthews algorithm
     */

    class JMQuasigroup : public Quasigroup {
    private:
        int **latinSquare;
    public:
        int getProduct(int x, int y) const override { return latinSquare[x][y]; };
        JMQuasigroup(int order, unsigned long long int seed);
        explicit JMQuasigroup(int order) : JMQuasigroup(order, time(nullptr)) {}
        explicit JMQuasigroup(std::ifstream &input);
        ~JMQuasigroup();
    protected:
        void generate() override;
    };

}


#endif //QUASIGROUP_JMQUASIGROUP_H
