#include "statistics/experiment/CheckPropertyTimeExperiment.h"
#include "statistics/experiment/GenerationTimeExperiment.h"
#include "statistics/experiment/QuantitiveExperiment.h"
#include "statistics/ExperimentsRunner.h"
#include "quasigroup/group/DihedralGroup.h"
#include "quasigroup/group/AlternatingGroup.h"
#include "quasigroup/group/AbelianGroup.h"
#include "generator/QuasigroupGenerator.h"
#include "quasigroup/factory/JMQuasigroupFactory.h"
#include "quasigroup/factory/SRQuasigroupFactory.h"
#include "quasigroup/factory/FNQuasigroupFactory.h"
#include "quasigroup/factory/PFQuasigroupFactory.h"
#include "quasigroup/factory/AffineQuasigroupFactory.h"
#include "quasigroup/square/JMQuasigroup.h"
#include "quasigroup/functional/PFQuasigroup.h"
#include "quasigroup/functional/SRQuasigroup.h"
#include "quasigroup/functional/FNQuasigroup.h"
#include "quasigroup/Quasigroup.h"
#include "quasigroup/square/AffineQuasigroup.h"
#include "function/AbelianGroupAutomorphism.h"
#include "transformer/KepkaTransformer.h"

int main() {
    return 0;
}
